"""Init

Revision ID: cf17a1de7477
Revises: 
Create Date: 2024-03-07 09:42:11.284364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf17a1de7477'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fn_groupid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fn_groupid'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fn_tutorid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fn_tutorid'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marks_tbl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('recieved', sa.Date(), nullable=False),
    sa.Column('fn_tutorid', sa.Integer(), nullable=False),
    sa.Column('fn_studentid', sa.Integer(), nullable=False),
    sa.Column('fn_subjectid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fn_studentid'], ['students.id'], ),
    sa.ForeignKeyConstraint(['fn_subjectid'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['fn_tutorid'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks_tbl')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('tutors')
    op.drop_table('groups')
    # ### end Alembic commands ###
